CREATE TABLE IF NOT EXISTS store_connections (
  id INT AUTO_INCREMENT PRIMARY KEY,
  store_url VARCHAR(255) NOT NULL UNIQUE,
  username VARCHAR(255) NOT NULL,
  auth_token TEXT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX (store_url)
); 